language: java

matrix:
  fast_finish: true
  include:
    # always build this environment
    - os: linux
      dist: xenial
      jdk: openjdk8
      services:
      - xvfb
      env: ADDITIONAL="-Pbuild-ide,test-ide"
    # only on PR, or after merging a PR
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11
      env: ADDITIONAL="-Pbuild-ide,test-ide"
      if: type IN (pull_request) OR commit_message =~ /^Merge pull request/

cache:
  directories:
    - '$HOME/.m2'

install: true

before_install:
 - echo $JAVA_HOME

# Build on MacOSX is triggered only for pull requests and merge of pull requests
script:
 - ./mvnw clean verify $ADDITIONAL


