/*
 * generated by Xtext 2.16.0
 */
package xklaim.tests;

import java.util.stream.Collectors;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.diagnostics.Severity;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.validation.Issue;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.inject.Inject;

import xklaim.xklaim.XklaimModel;

@RunWith(XtextRunner.class)
@InjectWith(XklaimInjectorProvider.class)
public class XklaimValidatorTest {

	@Inject
	ParseHelper<XklaimModel> parseHelper;
	@Inject
	ValidationTestHelper validationTestHelper;

	@Test
	public void testValidSelfLocality() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				proc TestProc() {
					out("hi")@self
				}
				"""));
	}

	@Test
	public void testValidLocality() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				import klava.Locality
				import klava.PhysicalLocality
				import klava.LogicalLocality
				
				proc TestProc(Locality l1, PhysicalLocality l2, LogicalLocality l3) {
					out("hi")@l1
					out("hi")@l2
					out("hi")@l3
				}
				"""));
	}

	@Test
	public void testInvalidLocality() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				proc TestProc(int i) {
					out("hi")@i
				}
				"""),
				"Type mismatch: cannot convert from int to Locality");
	}

	@Test
	public void testCanAccessFormalTupleFields() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in(var Integer i, s)@self
					println(i)
				}
				"""));
	}

	@Test
	public void testFormalTupleFieldMustHaveAType() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in(var i, s)@self
				}
				"""),
				"Type must be specified");
	}

	@Test
	public void testFormalTupleFieldCannotHaveInitialization() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in(var Integer i = 10, s)@self
				}
				"""),
				"Formal field must not be initialized");
	}

	@Test
	public void testCanUseValForFormalTupleFields() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in(val Integer i, s)@self
					println(i)
				}
				"""));
	}

	@Test
	public void testNonBlockingOperationAsStatement() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in_nb(val Integer i, s)@self
					read_nb(val Integer x, s)@self
					println(i)
				}
				"""));
	}

	@Test
	public void testNonBlockingOperationAsBooleanExpressionInIfStatement() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					if (in_nb(val Integer i, s)@self && !in_nb(val String l)@self) {
						println(l + i)
					} else {
						println(l + i)
					}
					if (read_nb(val Integer i, s)@self) {
						println(i)
					} else {
						println(i)
					}
				}
				"""));
	}

	@Test
	public void testTimeoutOperationAsBooleanExpressionInIfStatement() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					if ((in(val Integer i, s)@self within 1000) && (!in(val String l)@self within 1000)) {
						println(l + i)
					} else {
						println(l + i)
					}
					if (read(val Integer i, s)@self within 1000) {
						println(i)
					} else {
						println(i)
					}
				}
				"""));
	}

	@Test
	public void testTimeoutAsLong() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in(val Integer i, s)@self within 1000
					in(val Integer i2, s)@self within "foo"
				}
				"""),
				"Type mismatch: cannot convert from String to long");
	}

	@Test
	public void testNonBlockingInOperationAsBooleanExpressionInWhileStatementWithFinalVariable() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					while (in_nb(val Integer i, s)@self) {
						println(i)
					}
				}
				"""),
				"use 'var' instead of 'val' for formal field in loop's expression");
	}

	@Test
	public void testNonBlockingInOperationAsBooleanExpressionInBasicForLoopWithFinalVariable() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					for (;in_nb(val Integer i, s)@self;) {
						println(i)
					}
				}
				"""),
				"use 'var' instead of 'val' for formal field in loop's expression");
	}

	@Test
	public void testNonBlockingInOperationAsBooleanExpressionInWhileStatement() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					while (in_nb(var Integer i, s)@self) {
						println(i)
					}
				}
				"""));
	}

	@Test
	public void testNonBlockingInOperationAsBooleanExpressionInDoWhileStatement() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					do {
						println()
					} while (in_nb(val Integer i, s)@self)
				}
				"""));
	}

	@Test
	public void testFormalFieldsInNonBlockingInOperationAsBooleanExpressionAreNotVisibleOutside() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					if (in_nb(val Integer i, s)@self && !in_nb(val String l)@self) {
						
					}
					println(l + i)
				}
				"""),
				"""
				The method or field i is undefined
				The method or field l is undefined
				""");
	}

	@Test
	public void testDuplicateFormalFieldsInXklaimOperationInBooleanExpression() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					if (in_nb(var Integer i, s)@self && !in_nb(var String i)@self) {
						
					}
				}
				"""),
				"""
				Duplicate local variable i
				""");
	}

	@Test
	public void testDuplicateFormalFieldsInXklaimOperationAfterIf() throws Exception {
		validationTestHelper.assertNoErrors(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					if (in_nb(var Integer i, s)@self) {
						
					}
					in(var String i)@self
				}
				"""));
	}

	@Test
	public void testDuplicateFormalFieldsInXklaimOperation() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					in(var Integer i, s)@self
					in(var String i)@self
				}
				"""),
				"""
				Duplicate local variable i
				""");
	}

	@Test
	public void testInlineProcInOperations() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				
				proc TestProcess(String s) {
					var nonFinalVar = "a"
					val finalVar = "b"
					out(proc {
						var myLocalVar = "c"
						println(finalVar + nonFinalVar)
						println(s + finalVar + nonFinalVar + myLocalVar + self)
					},
					proc println(finalVar + nonFinalVar),
					s + finalVar + nonFinalVar)@self
				}
				"""));
	}

	@Test
	public void testInlineProcInVariable() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				
				proc TestProcess(String s) {
					var nonFinalVar = "a"
					val finalVar = "b"
					val P = proc {
						var myLocalVar = "c"
						println(finalVar + nonFinalVar)
						println(s + finalVar + nonFinalVar + myLocalVar + self)
					}
					out(P)@self
				}
				"""));
	}

	@Test
	public void testValidEvalOperation() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				
				proc P(String s) {
					
				}
				
				proc TestProcess(String s) {
					eval(new P("test"))@self
					eval(proc println("test"))@self
				}
				"""));
	}

	@Test
	public void testEvalOperationWithoutExplicitInnerProc() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				
				proc P(String s) {
					
				}
				
				proc TestProcess(String s) {
					eval("test")@self
				}
				"""));
	}

	@Test
	public void testCanAccessImplicitNetLogicalLocalities() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				net TestNet physical "tcp-127.0.0.1:9999" {
					node TestNode {
						println("Hello from " + TestNode)
					}
					node TestNodeWithLogLoc logical "foo" {
						println("Hello from " + foo)
					}
				}
				"""));
	}

	@Test
	public void testNetNodeWithEnvironment() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				net TestNet physical "tcp-127.0.0.1:9999" {
					node TestNodeWithEmptyEnvironment [] {
						println("Hello from " + TestNodeWithEmptyEnvironment)
					}
					node TestNodeWithEnvironment [next -> foo] {
						println("Hello from " + TestNodeWithEnvironment)
					}
					node TestNodeWithLogLoc logical "foo" {
						println("Hello from " + foo)
					}
				}
				"""));
	}

	@Test
	public void testNetNodeWithInvalidEnvironmentMappingToNonLocality() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				net TestNet physical "tcp-127.0.0.1:9999" {
					node TestNodeWithEnvironment [next -> "wrong"] {
						println("Hello from " + TestNodeWithEnvironment)
					}
				}
				"""),
				"Type mismatch: cannot convert from String to Locality");
	}

	@Test
	public void testCanAccessXklaimRuntimeUtilityMethods() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc Test() {
					val ll = logloc("test_log_loc")
					val pl = phyloc("test_phy_loc")
					println("" + ll + pl)
				}
				"""));
	}

	@Test
	public void testCanAccessKlavaClassesWithoutImport() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc Test() {
					val e = new Environment()
					val ee = new Environment.EnvironmentEntry(null, null)
					val KlavaProcess p = null
					println("" + e + ee + p)
				}
				"""));
	}

	@Test
	public void testOrOperationValid() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					or(proc in(var Integer i)@self, proc read(var String s2)@self)
				}
				"""));
	}

	@Test
	public void testOrOperationWithBlockBodiesValid() throws Exception {
		validationTestHelper.assertNoIssues(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					or(
						proc {
							in(var Integer i)@self
							println(i)
						},
						proc {
							read(var String s2)@self
							println(s2)
						}
					)
				}
				"""));
	}

	@Test
	public void testOrOperationWithOneArgumentIsInvalid() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					or(proc in(var Integer i)@self)
				}
				"""),
				"The 'or' operation requires at least 2 process arguments");
	}

	@Test
	public void testOrOperationWithNonRetrievalFirstOperationIsInvalid() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					or(proc out(s)@self, proc read(var String s2)@self)
				}
				"""),
				"The first operation of a process in 'or' must be 'in' or 'read'");
	}

	@Test
	public void testOrOperationWithBlockBodyNonRetrievalFirstOperationIsInvalid() throws Exception {
		assertErrorsAsStrings(parseHelper.parse("""
				package foo
				proc TestProcess(String s) {
					or(
						proc {
							out(s)@self
							in(var Integer i)@self
						},
						proc read(var String s2)@self
					)
				}
				"""),
				"The first operation of a process in 'or' must be 'in' or 'read'");
	}

	private void assertErrorsAsStrings(EObject o, CharSequence expected) {
		Assert.assertEquals(expected.toString().trim(),
				validationTestHelper.validate(o).stream()
						.filter(i -> i.getSeverity() == Severity.ERROR)
						.map(Issue::getMessage)
						.sorted()
						.collect(Collectors.joining("\n")));
	}
}
