/*
 * generated by Xtext 2.16.0
 */
package xklaim.tests;

import java.util.stream.Collectors;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.inject.Inject;

import xklaim.xklaim.XklaimModel;

@RunWith(XtextRunner.class)
@InjectWith(XklaimInjectorProvider.class)
public class XklaimParsingTest {

	@Inject
	ParseHelper<XklaimModel> parseHelper;

	@Test
	public void loadModel() throws Exception {
		var result = parseHelper.parse("""
				node test {}
				""");
		Assert.assertNotNull(result);
		var errors = result.eResource().getErrors();
		Assert.assertTrue(
				"Unexpected errors: " + errors.stream().map(Resource.Diagnostic::toString).collect(Collectors.joining(", ")),
				errors.isEmpty());
	}
}
