/*
 * generated by Xtext 2.16.0
 */
package xklaim.tests;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.inject.Inject;

import xklaim.xklaim.XklaimModel;

@RunWith(XtextRunner.class)
@InjectWith(XklaimInjectorProvider.class)
public class XklaimQualifiedNameProviderTest {

	@Inject
	ParseHelper<XklaimModel> parseHelper;
	@Inject
	IQualifiedNameProvider qualifiedNameProvider;

	@Test
	public void testFullyQualifiedNameWithoutPackage() throws Exception {
		Assert.assertNull(qualifiedNameProvider.getFullyQualifiedName(parseHelper.parse("""
				node test {}
				""")));
	}

	@Test
	public void testFullyQualifiedNameWithPackage() throws Exception {
		Assert.assertEquals("foo", qualifiedNameProvider.getFullyQualifiedName(parseHelper.parse("""
				package foo
				node test {}
				""")).toString());
	}
}
