/*
 * generated by Xtext 2.16.0
 */
package xklaim.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith
import xklaim.xklaim.XklaimModel
import org.eclipse.xtext.naming.IQualifiedNameProvider

import static extension org.junit.Assert.*

@RunWith(XtextRunner)
@InjectWith(XklaimInjectorProvider)
class XklaimQualifiedNameProviderTest {
	@Inject
	ParseHelper<XklaimModel> parseHelper
	@Inject extension IQualifiedNameProvider

	@Test
	def void testFullyQualifiedNameWithoutPackage() {
		assertNull(parseHelper.parse('''
			node test {}
		''').fullyQualifiedName)
	}

	@Test
	def void testFullyQualifiedNameWithPackage() {
		"foo".assertEquals(parseHelper.parse('''
			package foo
			node test {}
		''').fullyQualifiedName.toString)
	}
}
