/*
 * generated by Xtext 2.16.0
 */
package xklaim


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XklaimStandaloneSetup extends XklaimStandaloneSetupGenerated {

	def static void doSetup() {
		new XklaimStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
