/*
 * generated by Xtext 2.25.0
 */
package xklaim.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XklaimUiModule extends AbstractXklaimUiModule {

	public XklaimUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
