/*
 * generated by Xtext 2.16.0
 */
package xklaim.validation

import org.eclipse.xtext.xbase.XExpression
import xklaim.xklaim.XklaimAbstractOperation
import org.eclipse.emf.ecore.EObject

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XklaimValidator extends AbstractXklaimValidator {

	override protected isValueExpectedRecursive(XExpression expr) {
		return expr.eContainer instanceof XklaimAbstractOperation || super.isValueExpectedRecursive(expr)
	}

	override protected boolean isLocallyUsed(EObject target, EObject containerToFindUsage) {
		if (containerToFindUsage instanceof XklaimAbstractOperation) {
			// we don't want warning when a variable declaration appears as
			// formal field: it is implicitly used for the result
			return true;
		}
		return super.isLocallyUsed(target, containerToFindUsage);
	}
}
