/*
 * generated by Xtext 2.16.0
 */
package xklaim.validation

import org.eclipse.xtext.xbase.XExpression
import xklaim.xklaim.XklaimAbstractOperation

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XklaimValidator extends AbstractXklaimValidator {

	override protected isValueExpectedRecursive(XExpression expr) {
		return expr.eContainer instanceof XklaimAbstractOperation ||
			super.isValueExpectedRecursive(expr)
	}

}
