/**
 * generated by Xtext 2.16.0
 */
package xklaim.ui.labeling;

import static com.google.common.collect.Iterables.filter;
import static org.eclipse.xtext.xbase.lib.IterableExtensions.head;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.common.types.JvmGenericType;
import org.eclipse.xtext.xbase.jvmmodel.IJvmModelAssociations;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;

import com.google.inject.Inject;

import xklaim.xklaim.XklaimAbstractNode;
import xklaim.xklaim.XklaimNet;
import xklaim.xklaim.XklaimProcess;

/**
 * Provides labels for EObjects.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
public class XklaimLabelProvider extends XbaseLabelProvider {
	@Inject
	private IJvmModelAssociations associations;

	@Inject
	public XklaimLabelProvider(final AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	public String text(final XklaimProcess p) {
		return text(inferredJavaType(p));
	}

	public String image(final XklaimProcess p) {
		return "process_obj.gif";
	}

	public String text(final XklaimAbstractNode p) {
		return text(inferredJavaType(p));
	}

	public String image(final XklaimAbstractNode p) {
		return "node_obj.gif";
	}

	public String text(final XklaimNet p) {
		return text(inferredJavaType(p));
	}

	public String image(final XklaimNet p) {
		return "net_obj.gif";
	}

	private JvmGenericType inferredJavaType(final EObject e) {
		return head(
				filter(associations.getJvmElements(e), JvmGenericType.class));
	}
}
