/*
 * generated by Xtext 2.25.0
 */
package xklaim.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.common.types.JvmIdentifiableElement;
import org.eclipse.xtext.common.types.JvmType;
import org.eclipse.xtext.common.types.util.TypeReferences;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.eclipse.xtext.xbase.XExpression;
import org.eclipse.xtext.xbase.XbasePackage;
import org.eclipse.xtext.xbase.scoping.batch.IIdentifiableElementDescription;
import org.eclipse.xtext.xbase.typesystem.IBatchTypeResolver;
import org.eclipse.xtext.xbase.typesystem.IExpressionScope;
import org.eclipse.xtext.xbase.typesystem.IResolvedTypes;
import org.eclipse.xtext.xbase.typesystem.references.LightweightTypeReference;

import com.google.inject.Inject;

import klava.Locality;
import xklaim.xklaim.XklaimEvalOperation;
import xklaim.xklaim.XklaimInOperation;
import xklaim.xklaim.XklaimNonBlockingInOperation;
import xklaim.xklaim.XklaimNonBlockingReadOperation;
import xklaim.xklaim.XklaimOutOperation;
import xklaim.xklaim.XklaimReadOperation;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class XklaimProposalProvider extends AbstractXklaimProposalProvider {
	@Inject
	private IBatchTypeResolver batchTypeResolver;

	@Inject
	private TypeReferences typeReferences;

	@Override
	public void completeXFeatureCall_Feature(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		if (isLocalitySlot(model)) {
			completeLocalityProposals(model, context, acceptor);
			return;
		}
		super.completeXFeatureCall_Feature(model, assignment, context, acceptor);
	}

	protected void completeLocalityProposals(EObject model, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		if (!(model instanceof XExpression expression)) {
			return;
		}
		JvmType localityType = typeReferences.findDeclaredType(Locality.class, context.getResource());
		if (localityType == null) {
			return;
		}

		IResolvedTypes resolvedTypes = batchTypeResolver.resolveTypes(expression);
		IExpressionScope expressionScope = resolvedTypes.getExpressionScope(expression, IExpressionScope.Anchor.AFTER);
		getCrossReferenceProposalCreator().lookupCrossReference(expressionScope.getFeatureScope(), expression,
				XbasePackage.Literals.XABSTRACT_FEATURE_CALL__FEATURE, acceptor,
				input -> getFeatureDescriptionPredicate(context).apply(input) &&
					isLocalityCandidate(input, resolvedTypes, localityType),
				getProposalFactory(getFeatureCallRuleName(), context));
	}

	protected boolean isLocalitySlot(EObject model) {
		EObject current = model;
		while (current != null) {
			if (current instanceof XklaimOutOperation
					|| current instanceof XklaimInOperation
					|| current instanceof XklaimNonBlockingInOperation
					|| current instanceof XklaimReadOperation
					|| current instanceof XklaimNonBlockingReadOperation
					|| current instanceof XklaimEvalOperation) {
				return true;
			}
			current = current.eContainer();
		}
		return false;
	}

	protected boolean isLocalityCandidate(IEObjectDescription candidate, IResolvedTypes resolvedTypes, JvmType localityType) {
		if (!(candidate instanceof IIdentifiableElementDescription identifiableDescription)) {
			return false;
		}
		JvmIdentifiableElement element = identifiableDescription.getElementOrProxy();
		if (element == null) {
			return false;
		}
		LightweightTypeReference candidateType = resolvedTypes.getActualType(element);
		return candidateType != null && !candidateType.isPrimitiveVoid() && candidateType.isSubtypeOf(localityType);
	}
}
