/*
 * generated by Xtext 2.16.0
 */
package xklaim.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import xklaim.XklaimRuntimeModule
import xklaim.XklaimStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XklaimIdeSetup extends XklaimStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XklaimRuntimeModule, new XklaimIdeModule))
	}
	
}
