/**
 * generated by Xtext 2.16.0
 */
package xklaim.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import xklaim.xklaim.XklaimAbstractNode;
import xklaim.xklaim.XklaimProcess;

/**
 * Customization of the default outline structure.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class XklaimOutlineTreeProvider extends DefaultOutlineTreeProvider {
	public boolean _isLeaf(final XklaimProcess o) {
		return true;
	}

	public boolean _isLeaf(final XklaimAbstractNode o) {
		return true;
	}
}
