name: Java CI with Maven on Windows and Mac

on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest', 'windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
       java-version: 21
       distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        ./mvnw
        -f xklaim/xklaim.parent/pom.xml
        verify
        -Dskip.imc.tests=true -Dskip.klava.tests=true
        -Ptest-ide
      if: runner.os == 'macOS'
    - name: Build with Maven
      run: >
        .\mvnw.cmd
        -f xklaim/xklaim.parent/pom.xml
        verify
        '-Dskip.imc.tests=true' '-Dskip.klava.tests=true'
        '-Ptest-ide'
      if: runner.os == 'Windows'
#    - name: Archive Test Results
#      uses: actions/upload-artifact@v2
#      if: ${{ failure() || cancelled() }}
#      with:
#        name: test-results-${{ runner.os }}
#        path: '**/*.tests/target'
    - name: Archive UI Tests Screenshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: screenshots-${{ runner.os }}
        path: '**/*.tests/screenshots'
